### ISSUE TITLE
Handle Filters in Search Recipe API

### ISSUE THREAD

**Issue by Shubh-Nisar** [Shubh-Nisar/Recipe_Recommender#1]
https://github.com/Shubh-Nisar/Recipe_Recommender/blob/3d68002000afb4bc635bfc0c42c641148b161abb/Code/backend/controllers/recipe.js#L26-L36

**Comment by Neel317** [comment]
Does the API generate any response or is it a server error? 
Can you let me know the case when it is failing?

**Comment by Shubh-Nisar** [comment]
The API needs to be handled for cases where the user does not provide a filter for a specific category.

**Comment by Neel317** [comment]
The issue has been fixed. The API should be up and running now. Thanks
