### ISSUE TITLE
Infinite Action

### ISSUE THREAD

**Issue by Shubh-Nisar** [Shubh-Nisar/Recipe_Recommender#3]
Check this pipeline. The action runs for infinite time and has to be handled manually.

https://github.com/Shubh-Nisar/Recipe_Recommender/blob/0a191b06c9f6ea9e34f452660b3d1375af8ab80a/.github/workflows/coverage.yml#L34-L37

**Comment by Neel317** [comment]
Infinite action is fixed. The test cases were blocking the bash.
