### ISSUE TITLE
Filter restrictions

### ISSUE THREAD

**Issue by Shubh-Nisar** [Shubh-Nisar/Recipe_Recommender#4]
Form validation is blocking the user filters. For example, a user just names a recipe but does not want a budget constraint, he would not add a budget filter. 

https://github.com/Shubh-Nisar/Recipe_Recommender/blob/0a191b06c9f6ea9e34f452660b3d1375af8ab80a/Code/frontend/src/components/Form.js#L114-L157

**Comment by Neel317** [comment]
I have resolved this issue. Individual filters are now enabled.
